version: '2.1'
orbs: 

jobs:
  build_and_push_image_to_ecr:
  #ussing docker as executor
     docker:
       - image: cimg/python:3.10.5
     steps:
       - setup_remote_docker  #setting up a remote docker on which we can run our commands
       - checkout #checkout git repo
       - run: pip install awscli
       - run: 
            name: configure aws
            command: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_key $AWS_SECRET_ACCESS_KEY && aws configure set default.region $AWS_DEFAULT_REGION 
       - run:
            name: build and push images 
            command: |  
              docker build -t 310961312410.dkr.ecr.ap-south-1.amazonaws.com/test:$Version .
              #configure ecr to push images
              aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 310961312410.dkr.ecr.ap-south-1.amazonaws.com
              docker push 310961312410.dkr.ecr.ap-south-1.amazonaws.com/test:$Version
              aws ecr list-images --repository-name test
  establish_ssh_connection_and_pull_image:
     #here we are using aws linux server over which we can run our docker conatiners for deployment 
     machine:
        enabled: true
     steps:
        - checkout 
        - run:
            name: configure aws and ecr and then pull image     
            command: |
              scp .env $SSH_USER@$SSH_HOST:/tmp
              scp first.sh $SSH_USER@$SSH_HOST:/tmp 
              ssh $SSH_USER@$SSH_HOST "cd /tmp; chmod +x first.sh; sudo ./first.sh"
workflows:  
   for-tailcutter:
      jobs:
        - build_and_push_image_to_ecr:
            context: aws-credentials
            filters:
              branches:
                only:
                 - develop/mahle
        - establish_ssh_connection_and_pull_image:
            type: approval
            requires:
              - build_and_push_image_to_ecr
            context: 
              - ssh_coonection
              - aws-credentials
            filters:
              branches:
                only:
                 - develop/mahle
